"""Add area_responsable to solicitud

Revision ID: 7365db6e7bec
Revises: 7b4987c65ca5
Create Date: 2026-04-30 15:26:39.621940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7365db6e7bec'
down_revision: Union[str, Sequence[str], None] = '7b4987c65ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitud', sa.Column('area_responsable', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitud', 'area_responsable')
    # ### end Alembic commands ###
