"""Update solicitud table to match new model

Revision ID: 7b4987c65ca5
Revises: add_user_fields_20260423
Create Date: 2026-04-30 15:31:37.526647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b4987c65ca5'
down_revision: Union[str, Sequence[str], None] = 'add_user_fields_20260423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN for NULL constraints, so we'll use raw SQL
    # Make usuario_id nullable (recreate table in SQLite)
    op.execute("""
    CREATE TABLE solicitud_new (
        id INTEGER NOT NULL,
        radicado VARCHAR NOT NULL,
        tipo_solicitud VARCHAR NOT NULL,
        asunto VARCHAR NOT NULL,
        descripcion VARCHAR NOT NULL,
        ubicacion VARCHAR,
        documento VARCHAR,
        documento_basename VARCHAR,
        estado VARCHAR NOT NULL DEFAULT 'Radicada',
        fecha DATETIME NOT NULL,
        creado_por VARCHAR,
        usuario_id INTEGER,
        PRIMARY KEY (id),
        FOREIGN KEY(usuario_id) REFERENCES usuario (id)
    )
    """)

    # Copy data from old table to new table
    op.execute("""
    INSERT INTO solicitud_new (id, radicado, tipo_solicitud, asunto, descripcion, ubicacion, documento, documento_basename, estado, fecha, creado_por, usuario_id)
    SELECT id, radicado, tipo_solicitud, asunto, descripcion, ubicacion, documento, documento_basename, estado, fecha, creado_por, usuario_id
    FROM solicitud
    """)

    # Drop old table and rename new one
    op.drop_table('solicitud')
    op.rename_table('solicitud_new', 'solicitud')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back old columns
    op.add_column('solicitud', sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
    op.add_column('solicitud', sa.Column('fecha_respuesta', sa.DateTime(), nullable=True))
    op.add_column('solicitud', sa.Column('respuesta', sa.String(), nullable=True))
    op.add_column('solicitud', sa.Column('notas_internas', sa.String(), nullable=True))
    op.add_column('solicitud', sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True))
    op.add_column('solicitud', sa.Column('fecha_asignacion', sa.DateTime(), nullable=True))
    op.add_column('solicitud', sa.Column('funcionario_asignado_id', sa.INTEGER(), nullable=True))
    op.add_column('solicitud', sa.Column('clasificacion', sa.String(), nullable=True))
    op.add_column('solicitud', sa.Column('prioridad', sa.String(), nullable=True))

    # Remove new columns
    op.drop_column('solicitud', 'creado_por')
    op.drop_column('solicitud', 'fecha')
    op.drop_column('solicitud', 'documento_basename')
    op.drop_column('solicitud', 'radicado')
    # ### end Alembic commands ###
