"""Add respuesta field to solicitud

Revision ID: 9cd2274ba80b
Revises: 7365db6e7bec
Create Date: 2026-04-30 16:02:22.274718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd2274ba80b'
down_revision: Union[str, Sequence[str], None] = '7365db6e7bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitud', sa.Column('respuesta', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitud', 'respuesta')
    # ### end Alembic commands ###
